name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:openscad/releases
        sudo apt-get update
        sudo apt-get install openscad
        # Only works on Ubuntu >19.04:
        #   sudo apt install openscad

    - name: Build STLs
      run: make
